# Generated by Django 4.0.5 on 2022-06-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
                ('dueño', models.CharField(max_length=50)),
                ('tiempo', models.IntegerField()),
            ],
        ),
    ]
