# Generated by Django 4.0.5 on 2022-06-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='vip',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
